-- 
-- DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
-- 
-- Copyright 2017 the original author or authors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- Notice: this DDL is for HSQLDB

CREATE TABLE workflow (
    workflow_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    workflow_name VARCHAR(100) NOT NULL
);

CREATE TABLE job (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    job_status VARCHAR(10) NOT NULL,
    parameters LONGVARCHAR NOT NULL,
    output LONGVARCHAR,
    standard_output LONGVARCHAR, 
    workflow_id BIGINT NOT NULL,

    FOREIGN KEY (workflow_id) REFERENCES workflow (workflow_id)
);

CREATE TABLE job_dependency (
    job_id BIGINT,
    dependency_id BIGINT NOT NULL,
    
    PRIMARY KEY (job_id, dependency_id),
    FOREIGN KEY (job_id) REFERENCES job (job_id),
    FOREIGN KEY (dependency_id) REFERENCES Job (job_id)
);

CREATE TABLE task (
    job_id BIGINT,
    sequence_number INTEGER NOT NULL,

    class_name VARCHAR(1000) NOT NULL,
    parameters VARCHAR(10000),

    PRIMARY KEY (job_id, sequence_number),
    FOREIGN KEY (job_id) REFERENCES job (job_id)
);
