
-- Notice: this DDL is for HSQLDB

CREATE TABLE workflow (
    workflow_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    workflow_name VARCHAR(100) NOT NULL
);

CREATE TABLE job (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    job_status INTEGER NOT NULL,
    workflow_id BIGINT NOT NULL,

    FOREIGN KEY (workflow_id) REFERENCES workflow (workflow_id)
);

CREATE TABLE task (
    job_id BIGINT,
    sequence_number INTEGER NOT NULL,

    class_name VARCHAR(1000) NOT NULL,
    task_params VARCHAR(10000),

    PRIMARY KEY (job_id, sequence_number),
    FOREIGN KEY (job_id) REFERENCES job (job_id)
);
